In [183]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.datasets import load_breast_cancer

In [184]:
data= load_breast_cancer()

In [185]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [186]:
df= pd.DataFrame(data.data)

In [187]:
df.columns= [data.feature_names]

In [188]:
X=df

In [189]:
Y= pd.DataFrame(data.target)

In [190]:
Y

0
0    0
1    0
2    0
3    0
4    0
..  ..
564  0
565  0
566  0
567  0
568  1

[569 rows x 1 columns]

In [191]:
from sklearn.model_selection import train_test_split

In [192]:
X_train,X_test,Y_train,Y_test= train_test_split(X,Y,test_size=.3,random_state=44)

In [193]:
X_train.shape

(398, 30)

In [194]:
X_test.shape

(171, 30)

In [195]:
Y_train.shape

(398, 1)

In [196]:
Y_test.shape

(171, 1)

In [197]:
Y

0
0    0
1    0
2    0
3    0
4    0
..  ..
564  0
565  0
566  0
567  0
568  1

[569 rows x 1 columns]

# Logistic Regression

In [198]:
from sklearn.linear_model import LogisticRegression



In [199]:
LG= LogisticRegression()

In [200]:
LG.fit(X_train,Y_train)

LogisticRegression()

In [201]:
LG.intercept_

array([0.07977852])

In [278]:
LG.coef_

array([[-1.08460975e-01,  5.84650690e-02, -3.00541728e-03,
         2.48224704e+00, -1.98628063e+01,  2.89557385e+00,
         7.90327843e-03, -1.77124360e+00,  3.14853373e-01,
        -1.22351296e-02, -9.83264503e-01,  1.01770104e-02,
        -5.63189746e-01]])

In [203]:
# NEed to test the Model

predict =LG.predict(X_test)

In [204]:
#Compare the model prediction

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

import warnings
warnings.filterwarnings('ignore')

In [205]:
accuracy_score(predict,Y_test)

0.9707602339181286

In [206]:
confusion_matrix(predict,Y_test)

array([[ 59,   1],
       [  4, 107]], dtype=int64)

In [207]:
print(classification_report(predict,Y_test))

              precision    recall  f1-score   support

           0       0.94      0.98      0.96        60
           1       0.99      0.96      0.98       111

    accuracy                           0.97       171
   macro avg       0.96      0.97      0.97       171
weighted avg       0.97      0.97      0.97       171



# Ridge CLassification()

In [208]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV

R= Ridge()

In [209]:
parameters={'alpha':[1e-15,1e-10,1e-8,1e-3,1e-2,1e1,1e5,1e10,1e20,1e30,1e35,1e40,1e45,1e50,1e55,1e100]}

In [210]:
ridge= GridSearchCV(R,parameters,scoring='neg_mean_squared_error', cv=5)

In [211]:
ridge.fit(X,Y)

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.001, 0.01, 10.0,
                                   100000.0, 10000000000.0, 1e+20, 1e+30, 1e+35,
                                   1e+40, 1e+45, 1e+50, 1e+55, 1e+100]},
             scoring='neg_mean_squared_error')

In [212]:
ridge.best_params_

{'alpha': 0.01}

In [213]:
ridge.best_score_

-0.06353482471454908

# Boston house prediction

In [215]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [218]:
# For Linear Regression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [219]:
# For Logistics Regression

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [217]:
# Regression Models
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression

In [312]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

from sklearn.model_selection import cross_validate

In [221]:
# Lets work on continuous data
from sklearn.datasets import load_boston

In [222]:
data= load_boston()

In [223]:
data.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [224]:
x= pd.DataFrame(data.data)

In [226]:
x.columns= data.feature_names

In [228]:
x.shape

(506, 13)

In [229]:
y=data.target

In [231]:
y.shape

(506,)

In [234]:
y=y.reshape(-1,1)

In [235]:
y.shape

(506, 1)

In [242]:
# Simple Linear regression with Train_test

x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=.25,random_state=44)

In [243]:
x_train.shape

(379, 13)

In [244]:
y_train.shape

(379, 1)

In [245]:
x_test.shape

(127, 13)

In [246]:
y_test.shape

(127, 1)

In [292]:
# Get the fit line
LG= LinearRegression()

LG.fit(x_train,y_train)

LinearRegression()

In [294]:
LG.intercept_

array([44.69681327])

In [270]:
for i in LG.coef_:
    print(i)

[-1.08460975e-01  5.84650690e-02 -3.00541728e-03  2.48224704e+00
 -1.98628063e+01  2.89557385e+00  7.90327843e-03 -1.77124360e+00
  3.14853373e-01 -1.22351296e-02 -9.83264503e-01  1.01770104e-02
 -5.63189746e-01]


In [296]:
for i ,name in enumerate(x.columns):
    print(name ," have coefficients = ", LG.coef_[0][i] )

CRIM  have coefficients =  -0.10846097497642349
ZN  have coefficients =  0.05846506897139028
INDUS  have coefficients =  -0.0030054172794143227
CHAS  have coefficients =  2.482247038719293
NOX  have coefficients =  -19.86280634016594
RM  have coefficients =  2.8955738522036105
AGE  have coefficients =  0.007903278426414789
DIS  have coefficients =  -1.7712435966587188
RAD  have coefficients =  0.31485337295382293
TAX  have coefficients =  -0.012235129578972659
PTRATIO  have coefficients =  -0.9832645029122277
B  have coefficients =  0.010177010382446294
LSTAT  have coefficients =  -0.5631897462718812


In [298]:
# Validate the model
y_predict= LG.predict(x_test)

In [301]:
y_predict.shape

(127, 1)

In [302]:
y_test.shape

(127, 1)

In [303]:
LG.score(x_test,y_test)

0.7469657913158887

In [304]:
 r2_score(y_predict,y_test)

0.6047565786176368

In [306]:
mean_absolute_error(y_predict,y_test)

3.653919962137451

In [308]:
mse=mean_squared_error(y_predict,y_test)

In [310]:
rmse= np.sqrt(mse)

In [311]:
rmse

4.871575163129047

In [313]:
# Linear Regression with cross validate

mse= cross_validate(LG, x,y,scoring='neg_mean_squared_error', cv=5)

In [317]:
mse

{'fit_time': array([0.01998568, 0.00499678, 0.00299835, 0.00299954, 0.00299835]),
 'score_time': array([0.00399756, 0.00199866, 0.00199771, 0.00199747, 0.00099969]),
 'test_score': array([-12.46030057, -26.04862111, -33.07413798, -80.76237112,
        -33.31360656])}

# Ridge Regression

In [318]:
R= Ridge()

In [319]:
#  lambda values

parameters:{'alpha':[1e-15,1e-10,1e-8,1e-3,1e-2,1,5,10,20,30,35,40,45,50,55,100]}

In [320]:
RG=GridSearchCV(R,parameters,scoring='neg_mean_squared_error', cv=5)

In [321]:
RG.fit(x,y)

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.001, 0.01, 10.0,
                                   100000.0, 10000000000.0, 1e+20, 1e+30, 1e+35,
                                   1e+40, 1e+45, 1e+50, 1e+55, 1e+100]},
             scoring='neg_mean_squared_error')

In [322]:
RG.best_params_

{'alpha': 10.0}

In [323]:
RG.best_score_

-33.39522445903664

# LAsso Regression

In [324]:
from sklearn.linear_model import Lasso

In [325]:
L=Lasso()

In [327]:
LG= GridSearchCV(L,parameters, scoring='neg_mean_squared_error', cv=5)

In [328]:
LG.fit(x,y)

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.001, 0.01, 10.0,
                                   100000.0, 10000000000.0, 1e+20, 1e+30, 1e+35,
                                   1e+40, 1e+45, 1e+50, 1e+55, 1e+100]},
             scoring='neg_mean_squared_error')

In [329]:
LG.best_params_

{'alpha': 0.01}

In [330]:
LG.best_score_

-36.200735156751755