In [1]:
import numpy as np


In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
x=np.array([1,2,3,4,5])
x

output is :  array([1, 2, 3, 4, 5])
    
    what is the difference here?

array([1, 2, 3, 4, 5])

In [4]:
x

array([1, 2, 3, 4, 5])

In [5]:
x.shape

(5,)

In [9]:
x= np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [10]:
p=np.array([[11,12],[13,14]])
p

array([[11, 12],
       [13, 14]])

In [13]:
p.shape

(2, 2)

In [17]:
p=np.array([[11,12],[13,14],[15,16],[17,18]])
p


array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18]])

In [47]:
print(p)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [22]:
p=np.array([[11,12,13],[14,15,16]])
p
p.shape

(2, 3)

In [23]:
p=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
p
p.shape

(4, 4)

In [24]:
p.reshape(8,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [25]:
p.reshape(1,16)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]])

In [26]:
p.min()

1

In [27]:
p.max()

16

In [28]:
p.itemsize

4

In [33]:
p.dtype

dtype('int32')

In [34]:
p.data

In [35]:
p

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [40]:
p=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]],dtype='float64')
p

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]])

In [41]:
p.itemsize

8

In [43]:
y=np.arange(5,500,5)

In [45]:
y.shape

(99,)

In [49]:
a=y.reshape(33,3)

In [50]:
print(a)

[[  5  10  15]
 [ 20  25  30]
 [ 35  40  45]
 [ 50  55  60]
 [ 65  70  75]
 [ 80  85  90]
 [ 95 100 105]
 [110 115 120]
 [125 130 135]
 [140 145 150]
 [155 160 165]
 [170 175 180]
 [185 190 195]
 [200 205 210]
 [215 220 225]
 [230 235 240]
 [245 250 255]
 [260 265 270]
 [275 280 285]
 [290 295 300]
 [305 310 315]
 [320 325 330]
 [335 340 345]
 [350 355 360]
 [365 370 375]
 [380 385 390]
 [395 400 405]
 [410 415 420]
 [425 430 435]
 [440 445 450]
 [455 460 465]
 [470 475 480]
 [485 490 495]]


In [51]:
a.itemsize

4

In [52]:
a.size

99

In [55]:
x=np.arange(35).reshape(5,7)
x

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [56]:
x.reshape(7,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [57]:
print(x)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


In [59]:
x.ndim  #  no of dimensions

2

In [60]:
x.dtype

dtype('int32')

In [61]:
x.itemsize

4

In [62]:
x.size

35

In [63]:
type(x)

numpy.ndarray

In [72]:
b=np.array([[1.5548645154,2,3],[4,5,6]], dtype='float32')
b

array([[1.5548645, 2.       , 3.       ],
       [4.       , 5.       , 6.       ]], dtype=float32)

In [73]:
b.itemsize

4

In [69]:
b.size

6

In [74]:
b

array([[1.5548645, 2.       , 3.       ],
       [4.       , 5.       , 6.       ]], dtype=float32)

In [75]:
b.ravel()

array([1.5548645, 2.       , 3.       , 4.       , 5.       , 6.       ],
      dtype=float32)

In [76]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [77]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# 28 Nov-2021

In [1]:
# boradcasting in Numpy

In [3]:
import numpy as np

In [5]:
a= np.array([1,2,3,4])
b= np.array([1,2,3,4])

In [6]:
a+b

array([2, 4, 6, 8])

In [7]:
a*b

array([ 1,  4,  9, 16])

In [8]:
c=2.0

In [9]:
a*b*c

array([ 2.,  8., 18., 32.])

In [10]:
print(a*b*c)

[ 2.  8. 18. 32.]


In [11]:
a=np.array([20,30,40,50])
b=np.arange(4)

In [13]:
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [14]:
print(a-b)

[20 29 38 47]


In [15]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [67]:
b=np.random.random((2,2))

In [68]:
b

array([[0.00122421, 0.68855382],
       [0.57839426, 0.27414249]])

In [36]:
c=np.ones((2,3))
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [37]:
b+c

array([[1.12792548, 1.71974964, 1.43938233],
       [1.72878302, 1.39468809, 1.79078384]])

In [42]:
c=np.zeros((1,2))
c

array([[0., 0.]])

# Universal function

In [44]:
b=np.arange(3)

In [46]:
np.exp(b)

array([1.        , 2.71828183, 7.3890561 ])

In [47]:
np.sqrt(b)

array([0.        , 1.        , 1.41421356])

In [49]:
c=np.array((2,1,4))
c

array([2, 1, 4])

In [50]:
np.add(b,c)

array([2, 2, 6])

In [51]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
a[2:5]

array([2, 3, 4])

In [54]:
a[-1]

9

In [55]:
a[-2]

8

In [56]:
a[-4:]

array([6, 7, 8, 9])

In [57]:
a[-4:-2]

array([6, 7])

In [58]:
d2=np.arange(20)

In [59]:
d2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [60]:
d2[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [61]:
d3 =np.array([np.nan,1,2,3,np.nan,6,7,8  ])

In [62]:
d3

array([nan,  1.,  2.,  3., nan,  6.,  7.,  8.])

In [66]:
np.random.rand(2,2)  # uniform distribution --> similr like random

array([[0.46426898, 0.80920541],
       [0.96025977, 0.96950259]])

In [70]:
np.random.randn(2,3)

array([[-2.66207696,  0.1962336 , -1.09258418],
       [ 0.91494202,  1.06112115, -0.77323616]])

# Pandas

In [71]:
# Table like structure rows and columns

In [72]:
import pandas as pd

In [ ]:
# series  1-D (1 Vector) and DataFrame

In [73]:
a=pd.Series([1,2,3,4])

In [74]:
a

0    1
1    2
2    3
3    4
dtype: int64

In [75]:
b=pd.Series([55,66,88,99])
b

0    55
1    66
2    88
3    99
dtype: int64

In [82]:
c=pd.Series([1,2,3,4], index=['A','B','C','D'],dtype=float)

In [83]:
c

A    1.0
B    2.0
C    3.0
D    4.0
dtype: float64

In [86]:
c[0:3]

A    1.0
B    2.0
C    3.0
dtype: float64

In [92]:
data=np.array([1,2,3,4,5])
m=pd.Series(data,index=['a','b','c','d','e'])

In [93]:
m

a    1
b    2
c    3
d    4
e    5
dtype: int32

In [94]:
ckr={'name':'Mohit','runs':365,'over':6}

In [95]:
k=pd.Series(ckr)

In [96]:
k

name    Mohit
runs      365
over        6
dtype: object

In [97]:
data=[1,2,3,4]
df=pd.DataFrame(data)

In [98]:
df

0
0  1
1  2
2  3
3  4

In [99]:
data=[['Alex',10],['Bob',12],['Clarke',13]]

In [100]:
df=pd.DataFrame(data)

In [101]:
df

0   1
0    Alex  10
1     Bob  12
2  Clarke  13

In [102]:
df=pd.DataFrame(data, columns=['Name','Age'])

In [103]:
df

Name  Age
0    Alex   10
1     Bob   12
2  Clarke   13

In [104]:
print(df)

     Name  Age
0    Alex   10
1     Bob   12
2  Clarke   13


In [105]:
df=pd.DataFrame(data, columns=['Name','Age'], dtype=float)

In [106]:
df

Name   Age
0    Alex  10.0
1     Bob  12.0
2  Clarke  13.0

In [107]:
# another way to provide data

data={'Name':['Tom','Mohit','steve','Ricky'],'Age':[28,34,29,42]}

In [109]:
df= pd.DataFrame(data)
df

Name  Age
0    Tom   28
1  Mohit   34
2  steve   29
3  Ricky   42